local luasnip = require("luasnip")
require("luasnip.loaders.from_vscode").lazy_load("")
luasnip.filetype_extend("astro", {"html"})
luasnip.filetype_extend("javascriptreact", {"html"})
luasnip.filetype_extend("typescriptreact", {"html"})
